apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    name: wordpress
spec:
  containers:
    - image: wordpress
      name: wordpress
      env:
        - name: WORDPRESS_DB_PASSWORD
          # Change this - must match mysql.yaml password.
          value: testingitall
      ports:
        - containerPort: 80
          name: wordpress
      volumeMounts:
          # Name must match the volume name below.
        - name: wordpress-persistent-storage
          # Mount path within the container.
          mountPath: /var/www/html
  volumes:
    - name: wordpress-persistent-storage
      gcePersistentDisk:
        # This GCE persistent disk must already exist.
        pdName: wordpress-disk
        fsType: ext4
